resource "tls_private_key" "algadelivery-tofu" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "algadelivery-tofu" {
  key_name   = var.key_pair_name
  public_key = tls_private_key.algadelivery-tofu.public_key_openssh
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.algadelivery-tofu.private_key_pem
  filename        = "${path.module}/${var.key_pair_name}.pem"
  file_permission = "0400"
}

resource "aws_instance" "bastion" {
  ami                         = data.aws_ami.ubuntu.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.public["public_a"].id
  vpc_security_group_ids      = [aws_security_group.bastion.id]
  key_name                    = var.key_pair_name
  associate_public_ip_address = true

  tags = merge(
    local.common_tags,
    {
      Name = "${local.context_name}-bastion"
    }
  )

  depends_on = [aws_key_pair.algadelivery-tofu]
}

resource "aws_instance" "vm_private" {
  ami                         = data.aws_ami.ubuntu.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.private_management["private_a"].id
  vpc_security_group_ids      = [aws_security_group.security_group_private.id]
  key_name                    = var.key_pair_name
  associate_public_ip_address = true

  tags = merge(
    local.common_tags,
    {
      Name = "${local.context_name}-vm_private"
    }
  )

  depends_on = [aws_key_pair.algadelivery-tofu]
}